/*
 * ig: criminalshu
*/

export default {
  global: {
    switchLanguage: "Switch language / Sprache ändern",
    en: "English / Englisch",
    pl: "Polish / Polnisch",
    de: "German / Deutsch",
    currentlyChosen: "Currently chosen / Aktuell gewählt",
    updateAvailable: "Ein Update ist verfügbar",
    updateAvailableMore: "Die Seite wird in einem Moment neu geladen",
    status: "Status",
    github: "GitHub",
    discord: "Discord",
    noName: "(kein Name)",
  },
  pages: {
    activate: "Kontoaktivierung",
    auth: "Übersicht",
    bot: "Bot-Management",
    bots: "Deine Bots",
    connect: "Mit dem Konto verbinden",
    help: "Hilfe",
    loading: "Lädt...",
    logout: "Abmelden",
    home: "Startseite",
    illbient: "Illbient-Datenschutzerklärung",
    join: "Einladung zur Gruppe",
    notFound: "404",
    profile: "Dein Profil",
    premium: "Premium",
    forgot: "Passwortlose Anmeldung",
  },
  subheaders: {
    page: "Seite",
    panel: "Panel",
    other: "Andere",
  },
  activate: {
    inProgress: "Dein Konto wird aktiviert...",
    success: "Dein Konto wurde erfolgreich aktiviert!",
    successMore: "Du kannst jetzt zur Anmeldeseite gehen.",
    failed: "Die Aktivierung ist fehlgeschlagen!",
    failedMore: "Dein Konto wurde bereits aktiviert oder die Aktivierungszeit ist abgelaufen.",
    yourEmail: "Deine E-Mail-Andresse:",
    goNow: "Jetzt loslegen",
  },
  forgot: {
    inProgress: "Anmeldung bei deinem Konto...",
    success: "Du bist erfolgreich eingeloggt!",
    successMore: "Du kannst jetzt zum Ambient-Panel gehen.",
    failed: "Passwortloses Einloggen fehlgeschlagen!",
    failedMore: "Die Zeit für die passwortlose Anmeldung ist abgelaufen.",
  },
  join: {
    checkingInvite: "Einladung wird überprüft...",
    resolvedInvite: "Einladung zur Gruppe",
    invalidInvite: "Diese Einladung ist ungültig!",
    invalidInviteMore: "Die Einladung existiert nicht oder die Gruppe ist mit keinem Bot verbunden.",
    cardContent1: "Du wurdest eingeladen, der Gruppe beizutreten",
    cardContent2: "Gib den Link zu deinem Profil oder deinen Facebook-Benutzernamen ein, um dieser Gruppe automatisch beizutreten.",
    maleCount: "Männer",
    femaleCount: "Frauen",
    messagesCount: "Nachrichten",
    userBatch: "Profil-Link oder Nutzername",
    button: "Gruppe beitreten",
    immediateJoin: "Diese Gruppe hat keine manuelle Mitgliedsgenehmigung aktiviert oder der Bot ist ein Administrator, daher erhältst du sofort Zugang zur Gruppe",
    approvalRequired: "Diese Gruppe hat die manuelle Mitgliedsgenehmigung aktiviert und der Bot ist kein Administrator, daher kannst du erst nach Annahme der Anfrage auf die Gruppe zugreifen.",
    invitationId: "Einladung-ID:",
    invalidBatch: "Ungültiger Benutzerbatch!",
    notFound: "Nutzer nicht gefunden!",
    addedMale: "{0}, du wurdest zur Gruppe hinzugefügt!",
    addedFemale: "{0}, du wurdest zur Gruppe hinzugefügt!",
    addedMore: "Wenn du es nicht in den Konversationen siehst, überprüfe den Ordner 'Sonstige'.",
    alreadyAdded: "Du bist schon Mitglied dieser Gruppe!",
    premiumRequired: "Der Bot in dieser Gruppe hat kein Premium!",
    premiumRequiredMore: "Diese Funktion ist nur in Ambient Premium verfügbar.",
    alreadyQueued: "Du bist bereits in der Warteschlange!",
    alreadyQueuedMore: "Frag den Administrator, deine Beitrittsanfrage anzunehmen.",
    groupFull: "Die Gruppe hat bereits die maximale Anzahl an Mitgliedern erreicht!",
    groupFullMore: "Bitte den Administrator, inaktive Mitglieder aus der Gruppe zu entfernen.",
    queueFull: "Die Warteschlange der Mitglieder, die beitreten möchten, ist voll!",
    queueFullMore: "Bitte den Administrator, die Beitrittsanfragen zu prüfen.",
    privacyIssue: "Wir können dich nicht zur Gruppe hinzufügen!",
    privacyIssueMore: "Überprüfe deine Datenschutzeinstellungen.",
  },
  support: {
    fetching: "Abrufen Ihrer Support-Informationen...",
    invalid: "Ungültiger Support-Link",
    invalidMore: "Benutzer nicht gefunden.",
    premiumState: "Premium-Status",
    premiumInactive: "Inaktiv",
    premiumActive: "Aktiv bis {0}",
    selectLabel: "Monate und Betrag",
    percentOff: "{0}% Rabatt!",
    phoneNumber: "Telefonnummer",
    recipientAndTitle: "Empfänger und Titel",
    amount: "Betrag",
    copiedSuccessfullyPhoneNumber: "Telefonnummer erfolgreich kopiert!",
    copiedSuccessfullyRecipientAndTitle: "Empfänger und Titel erfolgreich kopiert!",
    copiedSuccessfullyAmount: "Betrag erfolgreich kopiert!",
    copiedSuccessfullyMore: "Vielen Dank für die Unterstützung von Ambient.",
    tip: "Du kannst Ambient jederzeit unterstützen und deine Premium-Mitgliedschaft verlängern. Wähle dazu unten den Betrag deiner Unterstützung und die Anzahl der Premium-Monate, die du erhalten möchtest.",
    transferPartOne: "Führe eine Telefonübertragung durch mit",
    transferPartTwo: "mit den folgenden Details:",
    perMonth: "pro Monat",
    cheaperBy: "günstiger um",
    rulesPartOne: "Durch die Durchführung einer Übertragung akzeptierst du den Inhalt des",
    rulesPartTwo: "Regeln zur Unterstützung von Ambient",
    whyWorth: "Warum ist es wert, es zu unterstützen?",
    tileTitle0: "Keine Einschränkungen",
    tileContent0: "Nutze alle Ambient-Funktionen ohne Einschränkungen.",
    tileTitle1: "Globale Vorteile",
    tileContent1: "Dein Premium umfasst alle Bots, die im Ambient-System erstellt wurden, und funktioniert in allen Gruppen",
    tileTitle2: "Gruppenverstärkung",
    tileContent2: "Du kannst bis zu 2 Gruppen verstärken, sodass alle ihre Mitglieder ebenfalls keine Einschränkungen haben.",
    tileTitle3: "Heb dich von der Masse ab",
    tileContent3: "Dein Premium-Status ist in deinen Profilinformationen sichtbar und zeigt, dass du Ambient unterstützt.",
    tileTitle4: "Hilfe mit Priorität",
    tileContent4: "Erhalte priorisierte Hilfe auf unserem Ambient-Community-Discord-Server.",
    tileTitle5: "Einfache Regeln",
    tileContent5: "Alles, was du tun musst, ist eine Telefonübertragung mit dem entsprechenden Betrag und Code, um Premium zu erhalten.",
    tileTitle6: "Erfahrung seit 2019",
    tileContent6: "Seit Jahren bieten wir Unterhaltungs- und Verwaltungstools für Hunderttausende von Nutzern und Zehntausende von Gruppen an.",
    tileTitle7: "Keine Werbung und Privatsphäre.",
    tileContent7: "Wir zeigen keine Werbung an und deine Daten bleiben sicher.",
    tileTitle8: "Einzigartig",
    tileContent8: "Ambient arbeitet in einem unvergleichlichen Maßstab und auf einem einzigartigen Niveau.",
    faq: "Häufig gestellte Fragen",
    faqTitle0: "Kann ich Premium an jemand anderen verschenken?",
    faqContent0:
      "Klar! Du musst nur ihre Kennung in den Feldern für Empfänger und Betreff anstelle deiner eigenen eingeben. Du kannst sie mit dem Befehl finden, der die Profilinformationen anzeigt.",
    faqTitle1: "In der App meiner Bank kann ich nur entweder den Empfänger oder den Betreff eingeben. Was soll ich tun?",
    faqContent1: "Füll einfach das Feld aus, das verfügbar ist.",
    faqTitle2: "Wie lange dauert es, bis ich Zugang zu Premium bekomme?",
    faqContent2: "Normalerweise innerhalb weniger Minuten, obwohl es in seltenen Fällen auch länger dauern kann. Wenn du auf Probleme stößt, kontaktiere uns auf unserem Discord-Server.",
    faqTitle3: "Kann ich die Unterstützung auch mit einer anderen Methode als der Telefonüberweisung leisten?",
    faqContent3: "Nein.",
    faqTitle4: "Für welche Bots und Gruppen gilt mein Premium?",
    faqContent4: "Aktives Premium funktioniert bei allen Bots, die im Ambient-System erstellt wurden, und in allen Gruppen. Du kannst alle Funktionen ohne Einschränkungen überall nutzen.",
    faqTitle5: "Wie funktioniert das Gruppen-Boosten?",
    faqContent5:
      "Mit aktivem Premium kannst du bis zu 2 Gruppen boosten. Dadurch können alle Mitglieder dieser Gruppen alle Ambient-Funktionen ohne Einschränkungen nutzen, auch wenn sie selbst kein aktives Premium haben. Du kannst deine Boosts jederzeit auf andere Gruppen übertragen.",
  },
  auth: {
    loginCardTitle: "Bereits Ambient nutzen? Anmelden:",
    email: "E-mail",
    password: "Password",
    passwordRepeat: "Password wiederholen",
    loginButton: "Anmelden",
    forgotPassword: "Password vergessen?",
    forgotPasswordModalHint:
      "Gib die E-Mail-Adresse ein, die mit deinem Konto verknüpft ist, um einen Link zum Einloggen ohne Passwort zu erhalten. Nach dem Einloggen kannst du im Profil-Tab ein neues Passwort festlegen.",
    registerCardTitle: "Neu bei Ambient? Jetzt registrieren!",
    registerButton: "Registrieren",
    activationMailNotReceived: "Aktivierungsmail nicht erhalten?",
    activationMailModalHint: "Gib die E-Mail-Adresse ein, die du bei der Registrierung angegeben hast, um einen Link zum erneuten Aktivieren deines Kontos zu erhalten.",
    checkMailbox: "Überprüfe dein Postfach, einschließlich des SPAM-Ordners.",
    activationMailError: "Konto existiert nicht, Aktivierungszeitraum ist abgelaufen oder es wurde bereits aktiviert!",
    forgotMailError: "Konto existiert nicht oder es wurde noch nicht aktiviert!",
    cancel: "Abbrechen",
    send: "Senden",
    invalidEmail: "Die angegebene E-Mail-Adresse ist ungültig!",
    passwordMismatch: "Die angegebenen Passwörter stimmen nicht überein!",
    correctAndTryAgain: "Bitte korrigiere die falschen Informationen und versuche es erneut.",
    confirmHuman: "Bitte bestätige, dass du kein Roboter bist.",
    confirmHumanMore: "Löse eine einfache Aufgabe und klicke dann auf den Bestätigungs-Button.",
    captchaNotSolved: "Aufgabenlösung abgebrochen",
    captchaNotSolvedMore: "Du musst die Aufgabe lösen, um zu bestätigen, dass du kein Roboter bist. Versuche es erneut.",
    captchaTimeout: "Die Zeit zum Lösen der Aufgabe ist abgelaufen!",
    captchaTimeoutMore: "Versuche es erneut.",
    verifySuccess: "Danke für die Bestätigung!",
    verifySuccessMore: "Daten überprüfen…",
    registerSuccess: "Erfolgreich registriert!",
    registerSuccessMore: "Wir haben eine Nachricht an die angegebene E-Mail-Adresse gesendet mit einem Link zur Aktivierung Ihres Kontos.",
    forgotSuccessMore: "Wir haben eine Nachricht an die angegebene E-Mail-Adresse gesendet mit einem Link, um sich ohne Passwort anzumelden.",
    registrationDisabled: "Die Registrierung ist derzeit deaktiviert!",
    registrationDisabledMore: "Tritt unserem Discord-Server bei, um mehr Informationen zu erhalten.",
    emailAlreadyExists: "Die angegebene E-Mail-Adresse ist bereits dem Konto zugeordnet!",
    emailAlreadyExistsMore: "Nutzen Sie die Möglichkeit, sich ohne Passwort anzumelden oder die Aktivierungs-E-Mail erneut zu senden.",
    unknownError: "Es ist ein unbekannter Fehler aufgetreten, bitte versuchen Sie es später erneut.",
    unknownErrorMore: "Wenn der Fehler weiterhin besteht, benachrichtige uns auf dem Discord-Server. Fehlercode: {0}",
    loginSuccess: "Willkommen im Ambient-Verwaltungsbereich!",
    loginSuccessMore: "Erfolgreich eingeloggt.",
    invalidEmailOrPassword: "Die angegebene E-Mail-Adresse oder das Passwort ist falsch!",
    deleteAccount: "Konto löschen",
    deleteAccountModalHint:
      "Bist du sicher, dass du dein Konto löschen möchtest? Wenn du dies tust, werden alle deine Daten unwiderruflich von unseren Servern gelöscht. Wenn du dich in Zukunft entscheidest, Ambient erneut zu nutzen, musst du ein neues Konto erstellen. Gib dein Passwort ein, um fortzufahren:",
    invalidPassword: "Das eingegebene Passwort ist falsch!",
    accountDeleted: "Dein Konto wurde erfolgreich gelöscht!",
    accountNotActivated: "Dein Konto wurde noch nicht aktiviert!",
    accountNotActivatedMore: "Keine Aktivierungs-E-Mail erhalten? Bitte nutze die Option - Erneut senden.",
    loggedOut: "Erfolgreich abgemeldet!",
    loggedOutMore: "Danke, dass du Ambient benutzt hast.",
    sessionExpired: "Deine Sitzung ist abgelaufen!",
    sessionExpiredMore: "Bitte melde dich erneut an.",
    passwordValidation: {
      min: "Das Passwort muss mindestens 12 Zeichen lang sein.",
      digits: "Das Passwort muss mindestens 2 Ziffern enthalten.",
      letters: "Das Passwort muss mindestens 6 Buchstaben enthalten.",
      lowercase: "Das Passwort muss mindestens 3 Kleinbuchstaben enthalten.",
      uppercase: "Das Passwort muss mindestens 1 Großbuchstaben enthalten.",
      symbols: "Das Passwort muss mindestens 1 Sonderzeichen enthalten.",
      spaces: "Das Passwort darf keine Leerzeichen enthalten.",
    },
  },
  profile: {
    infoCardTitle: "Konto",
    accountCreationDate: "Kontoerstellungsdatum",
    changePassword: "Passwort ändern",
    changePasswordModalHint: "Gib ein neues Passwort ein und wiederhole es zur Bestätigung.",
    newPassword: "Neues Passwort",
    newPasswordRepeat: "Neues Passwort wiederholen",
    changedSuccessfully: "Passwort erfolgreich geändert!",
    changedSuccessfullyMore: "Zum Anmelden musst du das neue Passwort verwenden.",
    premium: "Premium",
    premiumState: "Premium-Status",
    premiumInactive: "Inaktiv",
    premiumActive: "aktiv bis {0}",
    premiumId: "Premium-ID",
    copyToClipboard: "In die Zwischenablage kopieren",
    copiedSuccessfully: "Premium-ID erfolgreich in die Zwischenablage kopiert!",
    copiedSuccessfullyMore: "Danke, dass du Ambient unterstützt!",
    botsExist: "Du musst alle Bots löschen, bevor du dein Konto löschen kannst!",
    botsExistMore: "Lösche alle Bots und versuche es dann erneut.",
    address: "IP-Adresse",
    browser: "Browser",
    logDescriptions: {
      registered: "Das Konto wurde erfolgreich erstellt.",
      activated: "Das Konto wurde erfolgreich aktiviert.",
      passwordChanged: "Das Passwort wurde erfolgreich geändert.",
      forgotRequest: "Die Anfrage für einen Login-Link ohne Passwort wurde gesendet.",
      loginWrongPassword: "Es wurde versucht, sich mit dem falschen Passwort anzumelden.",
      loginSuccessUnactivated: "Es wurde versucht, sich anzumelden, bevor das Konto aktiviert wurde.",
      loginSuccessNormal: "Erfolgreich mit Passwort angemeldet.",
      loginSuccessPasswordless: "Erfolgreich mit einem Link ohne Passwort angemeldet.",
      resendRequest: "Eine Anfrage für einen Aktivierungslink wurde gesendet.",
      botCreated: "Neuer Bot wurde erfolgreich erstellt.",
      botDeleted: "Bot wurde erfolgreich gelöscht.",
    },
  },
  bots: {
    botsEmpty: "Du hast noch keine Bots. Erstelle einen neuen, um mit Ambient zu starten.",
    createBot: "Neuen Bot erstellen",
    botName: "Bot-Name",
    accountName: "Konto-Name",
    createBotModalHint: "Gib einen Namen für deinen Bot ein, du kannst ihn später ändern.",
    createdSuccessfully: "Bot wurde erfolgreich erstellt!",
    createdSuccessfullyMore: "Du kannst ihn jetzt mit einem Facebook-Konto verbinden.",
    renamedSuccessfully: "Bot wurde erfolgreich umbenannt!",
    renamedSuccessfullyMore: "Der neue Name wird nach dem Neustart des Bots berücksichtigt.",
    limitReached: "Du hast bereits die maximale Anzahl an Bots!",
    limitReachedMore: "Lösche unnötige Bots oder verwende einen der bestehenden.",
    limitReachedThreads: "Dieser Bot hat bereits die maximale Anzahl an erlaubten Threads erreicht!",
    limitReachedThreadsMore: "Lösche unnötige Threads, verwende den bestehenden oder nutze einen anderen Bot.",
    nameAlreadyUsed: "Der gewählte Name ist bereits vergeben!",
    action: "Aktion",
    manage: "Verwalten",
    backToList: "Zurück zur Bot-Liste",
    backToView: "Zurück zur Bot-Ansicht",
    invalidBot: "Der ausgewählte Bot existiert nicht!!",
    profilePicture: "Profilbild",
    info: "Info",
    fbAccountId: "Facebook-Konto-ID",
    currentInstance: "Aktuelle Instanz",
    showProfile: "Profil anzeigen",
    changeName: "Name ändern",
    allowedThreads: "Erlaubte Threads",
    threadName: "Thread-Name",
    threadPhoto: "Thread-Foto",
    participantsCount: "Teilnehmer",
    adminsCount: "Administratoren",
    hasThisBot: "Hat diesen Bot",
    yes: "Ja",
    no: "Nein",
    invitationLink: "Einladungslink",
    showInvitation: "Einladung anzeigen",
    copiedSuccessfully: "Einladungslink erfolgreich kopiert!",
    copiedSuccessfullyMore: "Du kannst ihn jetzt mit anderen teilen.",
    removeThread: "Thread entfernen",
    remove: "Entfernen",
    threadsEmpty: "Es wurden noch keine erlaubten Threads hinzugefügt",
    threadsNotRunning: "Um erlaubte Threads zu verwalten, muss der Bot ausgeführt werden",
    threadRemoved: "Thread erfolgreich aus der Liste der erlaubten Threads entfernt!",
    threadRemovedMore: "Der Bot kann in diesem Thread nicht mehr verwendet werden.",
    removeThreadModalHint: "Bist du sicher, dass du diesen Thread aus der Liste der erlaubten Threads entfernen möchtest? Dadurch können alle Mitglieder den Bot darin nicht mehr verwenden.",
    threadAdded: "Thread erfolgreich zur Liste der erlaubten Threads hinzugefügt!",
    threadAddedMore: "Der Bot kann jetzt in diesem Thread verwendet werden.",
    addThread: "Thread hinzufügen",
    add: "Hinzufügen",
    added: "Hinzugefügt",
    addThreadModalHint: "Wähle den Thread aus, den du zur Liste der erlaubten Threads hinzufügen möchtest. Dadurch können alle Mitglieder den Bot darin verwenden.",
    threadsLoading: "Warte, wir sammeln Informationen zu den Gruppen in der Konversationsliste des verbundenen Kontos. Dies kann einige Sekunden dauern....",
    threadsNotFound: "Wir haben keine freien Gruppen mit einem verbundenen Konto unter den Mitgliedern in der Konversationsliste gefunden.",
    state: "Status",
    done: "Fertig",
    screenshot: "Screenshot",
    screenshotModalHint:
      "Der Screenshot ermöglicht dir zu sehen, warum wir uns mit den angegebenen Zugangsdaten nicht anmelden konnten. Wenn sie falsch erscheinen, korrigiere sie und versuche es erneut. Du vermutest, dass der Anmeldeprozess nicht funktioniert? Kontaktiere uns auf dem Discord-Server, wir werden es so schnell wie möglich überprüfen.",
    failedReason: "Grund",
    failedReasonDescription: "Beschreibung",
    connection: "Kontoverbindung",
    connectionHint: "Verbinde den Bot mit deinem Facebook-Konto, um ihn zu nutzen. Um diese Option zu verwenden, muss der Bot deaktiviert sein.",
    screenshotHint: "Der Screenshot zeigt dir genau, was beim letzten Versuch, uns mit den von dir angegebenen Zugangsdaten in dein Konto einzuloggen, schiefgelaufen ist.",
    accountState: "Kontostatus",
    botState: "Bot-Status",
    start: "Start",
    stop: "Stop",
    dangerZone: "Gefahrenbereich",
    deleteBot: "Bot löschen",
    deleteHint: "Wenn du diesen Bot nicht mehr benötigst, kannst du ihn löschen. Um diese Option zu verwenden, muss der Bot deaktiviert sein.",
    deleteModalHint:
      "Bist du sicher, dass du diesen Bot löschen möchtest? Wenn du das tust, werden alle mit diesem Bot verbundenen Daten unwiderruflich von unseren Servern gelöscht. Um Ambient erneut zu nutzen, musst du einen neuen Bot erstellen.",
    disconnectAccount: "Konto trennen",
    disconnectHint: "Wenn du nicht möchtest, dass der Bot Zugriff auf dein Facebook-Konto hat, kannst du die Verbindung trennen. Um diese Option zu verwenden, muss der Bot deaktiviert sein.",
    disconnectModalHint:
      "Bist du sicher, dass du diesen Bot von deinem Facebook-Konto trennen möchtest? Wenn du das tust, kannst du den Bot nicht mehr ausführen, bis du ihn erneut mit einem Konto verbindest.",
    botDisconnected: "Das Konto wurde erfolgreich getrennt!",
    botDisconnectedMore: "Dieser Bot hat keinen Zugriff mehr auf dein Facebook-Konto.",
    botDeleted: "Der Bot wurde erfolgreich gelöscht!",
    botDeletedMore: "Du kannst jetzt einen neuen Bot erstellen.",
    invalidState: "Ungültiger Status!",
    invalidStateMore: "Der ausgewählte Bot befindet sich derzeit in einem Status, der es nicht erlaubt, ihn mit dem Konto zu verbinden.",
    connectionStarted: "Wir haben einen Versuch gestartet, den Bot mit dem Konto zu verbinden!",
    connectionStartedMore: "Es wird einige Sekunden dauern. Den aktuellen Status und die Ergebnisse kannst du auf dieser Seite einsehen.",
    username: "E-Mail-Adresse oder Telefonnummer",
    twoFactorAuthCode: "2FA-Code",
    usernameTooShort: "Der angegebene Benutzername ist zu kurz!",
    passwordTooShort: "Das angegebene Passwort ist zu kurz!",
    codeTooShort: "Der angegebene Zwei-Faktor-Authentifizierungscode ist zu kurz!",
    connectConfirmButton: "Bot mit Konto verbinden",
    importantCardCheckbox: "Einverstanden",
    understandNotChecked: "Wichtige Tipps lesen!",
    importantCardTitle: "Wichtig! Vor dem Verbinden lesen:",
    importantCardContents: [
      "Das Konto könnte von Facebook gesperrt werden, verwende daher nicht dein Hauptkonto, um es mit dem Bot zu verbinden.",
      "Es ist besser, ein Konto zu verwenden, das schon länger besteht und regulär genutzt wurde, als ein neues Konto zu erstellen und es sofort zur Verbindung mit dem Bot zu nutzen.",
      "Ein Konto, das mit echten Daten erstellt wurde und ein echtes Profilfoto hat, funktioniert am besten, da so deine Identität überprüft werden kann, wenn Facebook danach fragt.",
      "Wir empfehlen, dass du die Zwei-Faktor-Anmeldung (2FA) in deinen Kontoeinstellungen aktivierst. Dies erhöht die Wahrscheinlichkeit, den Bot erfolgreich mit deinem Konto zu verbinden, und verringert das Risiko, dass dein Konto aufgrund verdächtiger Aktivitäten gesperrt wird.",
      "Wir speichern die von dir angegebenen Anmeldedaten nicht. Sie werden nur von der automatisierten Software verwendet, um sich beim Konto anzumelden und eine Benutzersitzung zu erhalten, um das Konto mit dem Bot zu verbinden, und werden danach gelöscht.",
      "Die Verbindung des Bots mit dem Konto wird einige Sekunden dauern. Falls ein Problem auftritt, erhältst du Zugriff auf einen Screenshot von dem Anmeldeversuch, bei dem es aufgetreten ist. Du kannst ihn dann überprüfen, das Problem mit dem Konto lösen und es erneut versuchen.",
      "Beim Einloggen in dein Konto erhältst du möglicherweise eine Anmeldebenachrichtigung von einem neuen Standort im Safari-Browser auf einem iPhone. Diese stammt von unserem System und kann ignoriert werden.",
      "Es ist möglich, dass du beim Versuch, dich anzumelden, aufgefordert wirst, die Anmeldung zu bestätigen, zum Beispiel indem du das bei der Kontoerstellung angegebene Geburtsdatum eingibst. Melde dich dann wie gewohnt beim Konto an, beantworte die von Facebook gestellten Fragen und versuche anschließend erneut, den Bot mit dem Konto zu verbinden.",
    ],
    credentialsCardTitle: "Gib die Anmeldedaten deines Facebook-Kontos ein:",
    connConditions: {
      notConnected: "Nicht verbunden",
      connecting: "Verbindung wird hergestellt...",
      connected: "Verbunden",
    },
    connConditionsMore: {
      notConnected: "Um einen Bot zu starten, musst du ihn zuerst mit deinem Facebook-Konto verbinden.",
      connecting: "Wir versuchen, den Bot mit dem Facebook-Konto unter Verwendung der von dir angegebenen Anmeldedaten zu verbinden. Dies kann einige Sekunden dauern.",
      connected: "Wir haben den Bot erfolgreich mit deinem Facebook-Konto unter Verwendung der von dir angegebenen Anmeldedaten verbunden. Du kannst ihn jetzt starten.",
    },
    powerConditions: {
      starting: "Wird gestartet...",
      running: "Aktiv",
      stopping: "Wird gestoppt...",
      stopped: "Gestoppt",
    },
    powerConditionsMore: {
      starting: "Wir starten deinen Bot, das kann einige Sekunden dauern.",
      running: "Dein Bot ist gestartet und aktiv.",
      stopping: "Wir stoppen deinen Bot, das kann einige Sekunden dauern.",
      stopped: "Dein Bot ist derzeit gestoppt. Wenn das Konto verbunden ist, kannst du ihn starten.",
    },
    connFailedReasons: {
      badRequest: "Ungültige Anfrage",
      badCredentials: "Ungültige Anmeldedaten",
      unexpectedPage: "Unerwartete Seite",
      cUserMissing: "Benutzer fehlt",
      twoFactorAuthRequired: "Code erforderlich",
      badTwoFactorAuthCode: "Ungültiger Code",
      unknownError: "Unbekannter Fehler",
      alreadyUsed: "Konto verwendet",
    },
    connFailedReasonsMore: {
      badRequest: "Die gesendete Verbindungsanfrage ist fehlerhaft. Bitte versuche es später erneut und informiere uns auf dem Discord-Server, falls der Fehler weiterhin auftritt.",
      badCredentials: "Die angegebenen Anmeldedaten sind falsch. Bitte korrigiere sie und versuche es erneut.",
      unexpectedPage:
        "Beim Einloggen sind wir auf eine unerwartete Seite gestoßen. Bitte überprüfe den Screenshot und informiere uns auf dem Discord-Server, falls du vermutest, dass der Anmeldeprozess fehlerhaft ist.",
      cUserMissing: "Die resultierende Sitzung enthielt keine gültigen Kontoinformationen",
      twoFactorAuthRequired: "Wir haben uns erfolgreich eingeloggt, benötigen jedoch einen Zwei-Faktor-Anmeldecode, den du uns nicht bereitgestellt hast.",
      badTwoFactorAuthCode: "Wir konnten uns anmelden, aber der von dir eingegebene Zwei-Faktor-Authentifizierungscode ist falsch.",
      unknownError:
        "Beim Einloggen ist ein unerwarteter Fehler aufgetreten. Bitte überprüfe den Screenshot und informiere uns auf dem Discord-Server, falls du vermutest, dass der Anmeldeprozess fehlerhaft ist.",
      alreadyUsed: "Wir haben uns erfolgreich eingeloggt, aber dieses Konto wird bereits von einem anderen Bot verwendet. Bitte versuche es mit einem anderen Konto erneut.",
    },
    events: "Ereignisse",
    date: "Datum",
    description: "Beschreibung",
    logsEmpty: "Es wurden noch keine Ereignisse gemeldet.",
    logDescriptions: {
      created: "Der Bot wurde erfolgreich erstellt.",
      runRequest: "Start wird auf Benutzeranfrage ausgeführt.",
      autoRun: "Der automatische Start wurde aktiviert, um den vorherigen Zustand wiederherzustellen.",
      started: "Der Bot ist gestartet und aktiv.",
      stopRequest: "Stopp wird auf Benutzeranfrage ausgeführt.",
      stoppedLifecycle: "Gestoppt, da die Lebensdauer des Bots überschritten wurde.",
      stoppedManual: "Gestoppt auf Benutzeranfrage.",
      stoppedInactivity: "Gestoppt aufgrund längerer Inaktivität.",
      stoppedError: "Gestoppt aufgrund eines Fehlers. Versuche, den Bot erneut zu starten, und falls das Problem weiterhin besteht, verbinde das Konto erneut.",
      threadAdded: "Thread zur Liste der erlaubten Threads hinzugefügt.",
      threadRemovedManual: "Thread aus der Liste der erlaubten Threads entfernt.",
      threadRemovedAuto: "Thread aus der Liste der erlaubten Threads entfernt, da er in einem anderen Bot hinzugefügt wurde.",
      connectionStarted: "Ein Versuch gestartet, den Bot mit dem Konto zu verbinden.",
      connectionFailed: "Der Versuch, den Bot mit dem Konto zu verbinden, ist fehlgeschlagen.",
      connectionSuccess: "Der Bot wurde erfolgreich mit dem Konto verbunden. Du kannst ihn jetzt starten.",
      disconnected: "Der Bot wurde erfolgreich vom Konto getrennt.",
      renamed: "Bot-Name erfolgreich geändert.",
    },
  },
  help: {
    ytTutorial: "Anleitungsvideo auf YouTube",
    ytTutorialMore:
      "In diesem Video wird Dir gezeigt, wie du schnell und einfach deinen eigenen Ambient-Bot auf Messenger erstellst. Eine praktische Schritt-für-Schritt-Anleitung, die dich durch den gesamten Prozess führt.",
    discordServer: "Unser Discord-Server",
    discordServerMore:
      "Hast du noch Fragen oder brauchst du Hilfe? Tritt unserem Discord-Server bei, um mit der Ambient-Community zu chatten, Fragen zu stellen, Probleme zu melden und Unterstützung zu erhalten. Wir sprechen über alles – von Ideen für neue Funktionen bis hin zu lockeren Gesprächen. Du findest dort auch Updates, Events und Informationen darüber, was als Nächstes kommt.",
  },
};
