const language = {
  global: {
    switchLanguage: "Switch language / Zmień język",
    en: "English / angielski",
    pl: "Polish / polski",
    currentlyChosen: "Currently chosen / Obecnie wybrany",
    updateAvailable: "An update is available",
    updateAvailableMore: "The page will be reloaded in a moment",
    status: "Health",
    github: "GitHub",
    discord: "Discord",
    noName: "(no name)",
  },
  pages: {
    activate: "Account activation",
    auth: "Dashboard",
    bot: "Bot management",
    bots: "Your bots",
    connect: "Connect to an account",
    help: "Help",
    loading: "Loading...",
    logout: "Log out",
    home: "Home",
    join: "Invitation to the group",
    notFound: "404",
    profile: "Your profile",
    premium: "Premium",
    forgot: "Passwordless login",
  },
  subheaders: {
    page: "Page",
    panel: "Panel",
    other: "Other",
  },
  activate: {
    inProgress: "Your account is being activated...",
    success: "Your account has been successfully activated!",
    successMore: "You can now go to the login page.",
    failed: "Activation failed!",
    failedMore: "Your account has already been activated or the account activation time has expired.",
    yourEmail: "Your e-mail address:",
    goNow: "Go now",
  },
  forgot: {
    inProgress: "Logging in to your account...",
    success: "Successfully logged into your account!",
    successMore: "You can now go to the Ambient management panel.",
    failed: "Passwordless login failed!",
    failedMore: "Passwordless login time has expired.",
  },
  join: {
    checkingInvite: "Checking invitation...",
    resolvedInvite: "Invitation to join the group",
    invalidInvite: "You cannot use this invitation!",
    invalidInviteMore: "The invitation does not exist or the group is not connected to any bot.",
    cardContent1: "You have been invited to join the group",
    cardContent2: "Enter your profile link or Facebook username to automatically join this group:",
    maleCount: "Males",
    femaleCount: "Females",
    messagesCount: "Messages",
    userBatch: "Profile link or username",
    button: "Join to the group",
    immediateJoin: "This group doesn't have manual member approval enabled or the bot is an admin, so you'll get access to the group immediately.",
    approvalRequired: "This group has manual member approval enabled and the bot is not an admin, so you will only be able to access the group after accepting the request.",
    invitationId: "Invitation ID:",
    invalidBatch: "Invalid user batch!",
    notFound: "User was not found!",
    addedMale: "{0}, you have been added to the group!",
    addedFemale: "{0}, you have been added to the group!",
    addedMore: "If you don't see it in conversations, check the others folder.",
    alreadyAdded: "You are already a member of this group!",
    premiumRequired: "Bot enabled in this group does not have Premium!",
    premiumRequiredMore: "This feature is only available in Ambient Premium.",
    alreadyQueued: "You are already in the queue!",
    alreadyQueuedMore: "Ask the administrator to accept your join request.",
    groupFull: "The group already has the maximum number of members!",
    groupFullMore: "Ask the administrator to remove inactive members from the group.",
    queueFull: "The queue of members to join is full!",
    queueFullMore: "Ask the administrator to review join requests.",
    privacyIssue: "We can't add you to the group!",
    privacyIssueMore: "Check your privacy settings.",
  },
  auth: {
    loginCardTitle: "Already using Ambient? Sign in:",
    email: "E-mail",
    password: "Password",
    passwordRepeat: "Repeat password",
    loginButton: "Sign in",
    forgotPassword: "Forgot password?",
    forgotPasswordModalHint:
      "Enter the email address associated with your account to receive a link to log in without a password. After logging in, you will be able to set a new password in the your profile tab.",
    registerCardTitle: "New to Ambient? Sign up now!",
    registerButton: "Sign up",
    activationMailNotReceived: "Activation mail not received?",
    activationMailModalHint: "Enter the e-mail address provided during registration to receive a link to activate your account again.",
    checkMailbox: "Check your inbox including the SPAM folder",
    activationMailError: "Account does not exist, activation time has expired, or it has already been activated!",
    forgotMailError: "Account does not exist or it has not been activated!",
    cancel: "Cancel",
    send: "Send",
    invalidEmail: "The e-mail address provided is not valid!",
    passwordMismatch: "The given passwords do not match!",
    correctAndTryAgain: "Please correct the wrong information and try again.",
    confirmHuman: "Please confirm that you are not a robot",
    confirmHumanMore: "Solve a simple task and then click the verify button.",
    captchaNotSolved: "Task solving aborted",
    captchaNotSolvedMore: "You have to solve the task to confirm that you are not a robot. Try again.",
    captchaTimeout: "The time to solve task is over!",
    captchaTimeoutMore: "Try again.",
    verifySuccess: "Thanks for confirmation!",
    verifySuccessMore: "Checking data...",
    registerSuccess: "Successfully registered!",
    registerSuccessMore: "We have sent a message to the e-mail address provided with a link to activate your account.",
    forgotSuccessMore: "We have sent a message to the e-mail address provided with a link to sign in without password.",
    registrationDisabled: "Registration is currently disabled!",
    registrationDisabledMore: "Join our Discord server for more information.",
    emailAlreadyExists: "The e-mail address provided is already assigned to the account!",
    emailAlreadyExistsMore: "Use the option of logging in without a password or resending the activation e-mail.",
    unknownError: "An unknown error has occurred, please try again later.",
    unknownErrorMore: "If the error persists, notify us on the Discord server. Error code: {0}",
    loginSuccess: "Welcome to the Ambient management panel!",
    loginSuccessMore: "Logged in successfully.",
    invalidEmailOrPassword: "The given e-mail address or password is incorrect!",
    deleteAccount: "Delete account",
    deleteAccountModalHint:
      "Are you sure you want to delete your account? If you do this, all your data will be irretrievably deleted from our servers. If you decide to use Ambient again in the future, you will need to create a new account. Enter your password to continue:",
    invalidPassword: "The given password is incorrect!",
    accountDeleted: "Your account has been deleted successfully!",
    accountNotActivated: "Your account has not been activated!",
    accountNotActivatedMore: "Activation mail not received? Please use the resend option.",
    loggedOut: "Logged out successfully!",
    loggedOutMore: "Thank you for using Ambient.",
    sessionExpired: "Your session has expired!",
    sessionExpiredMore: "Please login again.",
    passwordValidation: {
      min: "Password must be at least 12 characters long.",
      digits: "Password must contain at least 2 digits.",
      letters: "Password must contain at least 6 letters.",
      lowercase: "Password must contain at least 3 lowercase letters.",
      uppercase: "Password must contain at least 1 uppercase letter.",
      symbols: "Password must contain at least 1 special character.",
      spaces: "Password cannot contain spaces.",
    },
  },
  profile: {
    infoCardTitle: "Account",
    accountCreationDate: "Account creation date",
    changePassword: "Change password",
    changePasswordModalHint: "Enter a new password and then re-enter it for verification.",
    newPassword: "New password",
    newPasswordRepeat: "Repeat new password",
    changedSuccessfully: "Password changed successfully!",
    changedSuccessfullyMore: "To log in you must use the new password.",
    premium: "Premium",
    premiumState: "Premium state",
    premiumInactive: "inactive",
    premiumActive: "active until {0}",
    premiumId: "Premium ID",
    copyToClipboard: "Copy to clipboard",
    copiedSuccessfully: "Successfully copied Premium ID!",
    copiedSuccessfullyMore: "Thank you for supporting Ambient.",
    botsExist: "You must delete all bots before deleting your account!",
    botsExistMore: "Delete all bots and then try again.",
    address: "IP address",
    browser: "Browser",
    logDescriptions: {
      registered: "The account has been successfully created.",
      activated: "The account has been successfully activated.",
      passwordChanged: "The password has been successfully changed.",
      forgotRequest: "Request for link to login without password has been sent.",
      loginWrongPassword: "Attempted to log in with the wrong password.",
      loginSuccessUnactivated: "Attempted to log in before activating the account.",
      loginSuccessNormal: "Successfully logged in with a password.",
      loginSuccessPasswordless: "Successfully logged in with a link without a password.",
      resendRequest: "A request for a link to activate the account has been sent.",
      botCreated: "New bot successfully created.",
      botDeleted: "Bot has been successfully deleted.",
    },
  },
  bots: {
    botsEmpty: "You don't have any bots yet, create a new one to start using Ambient.",
    createBot: "Create new bot",
    botName: "Bot name",
    accountName: "Account name",
    createBotModalHint: "Enter a name for your bot, you can change it later.",
    createdSuccessfully: "Bot has been successfully created!",
    createdSuccessfullyMore: "You can now connect it to a Facebook account.",
    renamedSuccessfully: "Bot has been successfully renamed!",
    renamedSuccessfullyMore: "New name will be taken into account after the bot is restarted.",
    limitReached: "You already have the maximum number of bots!",
    limitReachedMore: "Delete unnecessary bots or use the existing one.",
    limitReachedThreads: "This bot already has the maximum number of allowed threads!",
    limitReachedThreadsMore: "Remove unnecessary threads, use the existing one, or use a different bot.",
    nameAlreadyUsed: "The name chosen is already taken!",
    action: "Action",
    manage: "Manage",
    backToList: "Back to the bot list",
    backToView: "Back to the bot view",
    invalidBot: "Selected bot does not exist!",
    profilePicture: "Profile picture",
    info: "Info",
    fbAccountId: "Facebook account ID",
    currentInstance: "Current instance",
    showProfile: "Show profile",
    changeName: "Change name",
    allowedThreads: "Allowed threads",
    threadName: "Thread name",
    threadPhoto: "Thread photo",
    participantsCount: "Participants",
    adminsCount: "Admins",
    hasThisBot: "Has this bot",
    yes: "yes",
    no: "no",
    invitationLink: "Invitation link",
    showInvitation: "Show invitation",
    copiedSuccessfully: "Successfully copied invitation link!",
    copiedSuccessfullyMore: "You can now share it with others.",
    removeThread: "Remove thread",
    remove: "Remove",
    threadsEmpty: "No allowed threads have been added yet.",
    threadsNotRunning: "To manage allowed threads, the bot must be running.",
    threadRemoved: "Successfully removed thread from the allowed list!",
    threadRemovedMore: "The bot can no longer be used on this thread.",
    removeThreadModalHint: "Are you sure you want to remove this thread from the allowed list? This will prevent all members from using the bot in it.",
    threadAdded: "Successfully added thread to the allowed list!",
    threadAddedMore: "The bot can now be used on this thread.",
    addThread: "Add thread",
    add: "Add",
    added: "Added",
    addThreadModalHint: "Select the thread you want to add to the allowed list. This will allow all members to use the bot in it.",
    threadsLoading: "Wait, we're collecting information on the groups on the connected account's conversation list. This may take several seconds...",
    threadsNotFound: "We did not find any free groups with a connected account in the members in the conversation list.",
    state: "State",
    done: "Done",
    screenshot: "Screenshot",
    screenshotModalHint:
      "Sscreenshot allows you to see why we were unable to log in with the provided credentials. If they appear to be incorrect, correct them and try again. You suspect that the login process is malfunctioning? Contact us on the Discord server, we'll look into it asap.",
    connection: "Account connection",
    connectionHint: "Connect bot with your Facebook account to start using it. To use this option, bot must be turned off.",
    screenshotHint: "Screenshot lets you see what exactly went wrong the last time we tried to log into your account with the credentials you provided.",
    accountState: "Account state",
    botState: "Bot state",
    start: "Start",
    stop: "Stop",
    invalidState: "Invalid state!",
    invalidStateMore: "The selected bot is currently in a state that does not allow it to connect it with the account.",
    connectionStarted: "We have started an attempt to connect the bot with the account!",
    connectionStartedMore: "It will take several seconds, the current status and results can be seen on this page.",
    username: "E-mail address or phone no.",
    twoFactorAuthCode: "2FA code",
    usernameTooShort: "The given username is too short!",
    passwordTooShort: "The given password is too short!",
    codeTooShort: "The given two factor auth code is too short!",
    connectConfirmButton: "Connect bot with account",
    importantCardCheckbox: "I understand",
    understandNotChecked: "Read important tips!",
    importantCardTitle: "Important! Read before connecting:",
    importantCardContents: [
      "The account may be blocked by Facebook, so do not use your main account to connect it with the bot.",
      "It is better to use an account that was created some time ago and was used normally than to create a new account and use it to connect to the bot right away.",
      "An account created with real data and with a real profile photo set will work best, as it will be possible to verify your identity when Facebook requests it.",
      "We recommend that you enable two-factor login using the 2FA code in your account settings, it will increase the chance of successfully connecting the bot to your account and reduce the chance of your account being blocked due to suspicious activity.",
      "We do not store the login details you provide. They will only be used to log into the account by automated software in order to try to obtain a user session to connect the account with the bot, then they are forgotten.",
      "Connecting the bot with the account will take several seconds, if we encounter a problem, you will get access to the screenshot from the login stage where this occurred, you can then review it, solve any problem with the account and try again.",
      "When logging into your account, you may receive a login notification from a new location in the Safari browser on iPhone device, it comes from our system and should be ignored.",
      "It is possible that when you try to log in, you will be asked to approve it, and enter, for example, the date of birth provided when creating the account, then log in to the account as normal, answer the questions asked by Facebook, and then try to connect the bot to the account again.",
    ],
    credentialsCardTitle: "Enter Facebook account login details:",
    connConditions: {
      notConnected: "Not connected",
      connecting: "Connecting...",
      connected: "Connected",
    },
    connConditionsMore: {
      notConnected: "To start a bot, you first need to connect it to your Facebook account.",
      connecting: "We are trying to connect the bot with the Facebook account using the login details provided by you, it may take several seconds.",
      connected: "We have successfully connected the bot to your Facebook account using the login credentials you provided, you can now start it.",
    },
    powerConditions: {
      starting: "Starting...",
      running: "Running",
      stopping: "Stopping...",
      stopped: "Stopped",
    },
    powerConditionsMore: {
      starting: "We're starting your bot, it may take several seconds.",
      running: "Your bot is up and running.",
      stopping: "We're stopping your bot, this may take several seconds.",
      stopped: "Your bot is currently stopped. If the account is connected, you can start it.",
    },
    connFailedReasons: {
      badRequest: "Bad request",
      badCredentials: "Invalid credentials",
      unexpectedPage: "Unexpected page",
      cUserMissing: "User missing",
      twoFactorAuthRequired: "Code required",
      badTwoFactorAuthCode: "Invalid code",
      unknownError: "Unknown error",
      alreadyUsed: "Account used",
    },
    connFailedReasonsMore: {
      badRequest: "Connection request sent is incorrect, please try again later and notify us on the Discord server if the error persists.",
      badCredentials: "The credentials provided are incorrect, please correct them and try again.",
      unexpectedPage:
        "We encountered an unexpected page while logging in, please review the screenshot and notify us on the Discord server if you suspect that the login process is malfunctioning.",
      cUserMissing: "Resulting session did not contain valid account information",
      twoFactorAuthRequired: "We have successfully logged in, but we need a two factor login code which you did not provide us with.",
      badTwoFactorAuthCode: "We were able to sign in, but the two factor auth code you entered is incorrect.",
      unknownError:
        "We encountered an unexpected error while logging in, please review the screenshot and notify us on the Discord server if you suspect that the login process is malfunctioning.",
      alreadyUsed: "We have successfully logged in, but this account is already in use by another bot. Please try again with a different account.",
    },
    events: "Events",
    date: "Date",
    description: "Description",
    logsEmpty: "No events have been reported yet.",
    logDescriptions: {
      created: "The bot has been successfully created.",
      runRequest: "Starting due to user request.",
      autoRun: "Auto startup has been initiated to restore the previous state.",
      started: "Bot is up and running.",
      stopRequest: "Stopping due to user request.",
      stoppedLifecycle: "Stopped because bot lifecycle has been exceeded.",
      stoppedManual: "Stopped due to user request.",
      stoppedInactivity: "Stopped due to inactivity for a long time.",
      stoppedError: "Stopped beacause of an error, try to run the bot and if the problem persists, reconnect the account.",
      threadAdded: "Added thread to the allowed list.",
      threadRemovedManual: "Removed thread from the allowed list.",
      threadRemovedAuto: "Removed thread from the allowed list because it was added in another bot.",
      connectionStarted: "Started an attempt to connect the bot with the account.",
      connectionFailed: "An attempt to connect the bot to the account has failed.",
      connectionSuccess: "Successfully connected bot to the account, you can start it now.",
      disconnected: "Successfully disconnected bot from the account.",
      renamed: "Successfully changed bot name.",
    },
  },
};

export default language;
