const language = {
  global: {
    switchLanguage: "Zmień język / Switch language",
    en: "angielski / English",
    pl: "polski / Polish",
    currentlyChoosen: "Obecnie wybrany / Currently choosen",
    updateAvailable: "Dostępna jest aktualizacja",
    updateAvailableMore: "Za chwilę nastąpi przeładowanie strony",
    discord: "Serwer Discord",
  },
  pages: {
    activate: "Aktywacja konta",
    auth: "Panel",
    bot: "Zarządzanie botem",
    bots: "Twoje boty",
    connect: "Połącz z kontem",
    help: "Pomoc",
    loading: "Ładowanie...",
    logout: "Wyloguj się",
    home: "Strona główna",
    notFound: "404",
    profile: "Twój profil",
    premium: "Premium",
  },
  subheaders: {
    page: "Strona",
    panel: "Panel",
    other: "Inne",
  },
  activate: {
    inProgress: "Trwa aktywacja Twojego konta...",
    success: "Twoje konto zostało pomyślnie aktywowane!",
    successMore: "Za chwilę nastąpi przekierowanie na stronę logowania.",
    failed: "Aktywacja nie powiodła się!",
    failedExpired: "Twoje konto zostało już aktywowane lub upłynął czas na aktywację konta.",
    failedError: "Wystąpił nieznany błąd, spróbuj ponownie później. Jeśli błąd będzie się powtarzał, powiadom nas na serwerze Discord.",
    yourEmail: "Twój adres e-mail:",
    goNow: "Przejdź teraz",
  },
  auth: {
    loginCardTitle: "Korzystasz już z Ambienta? Zaloguj się:",
    email: "Adres e-mail",
    password: "Hasło",
    passwordRepeat: "Powtórz hasło",
    loginButton: "Zaloguj się",
    forgotPassword: "Nie pamiętasz hasła?",
    forgotPasswordModalHint:
      "Podaj adres e-mail przypisany do Twojego konta, aby otrzymać link umożliwiający zalogowanie się bez hasła. Po zalogowaniu ustawienie nowego hasła będzie możliwe w zakładce Twojego profilu.",
    registerCardTitle: "Nowy w Ambiencie? Zarejestruj się teraz!",
    registerButton: "Zarejestruj się",
    activationMailNotReceived: "Mail aktywacyjny nie doszedł?",
    activationMailModalHint: "Podaj adres e-mail podany przy rejestracji, aby ponownie otrzymać link do aktywacji Twojego konta.",
    checkMailbox: "Sprawdź skrzynkę odbiorczą",
    activationMailError: "Konto nie istnieje, upłynął czas na aktywację, lub zostało już aktywowane!",
    cancel: "Anuluj",
    send: "Wyślij",
    invalidEmail: "Podany adres e-mail jest nieprawidłowy!",
    passwordMismatch: "Podane hasła nie zgadzają się!",
    correctAndTryAgain: "Popraw błędne informacje i spróbuj ponownie.",
    confirmHuman: "Potwierdź, że nie jesteś robotem",
    confirmHumanMore: "Rozwiąż proste zadanie, a następnie kliknij przycisk weryfikuj.",
    captchaNotSolved: "Przerwano rozwiązywanie zadania",
    captchaNotSolvedMore: "Musisz rozwiązać zadanie aby potwierdzić, że nie jesteś robotem. Spróbuj ponownie.",
    captchaTimeout: "Czas na rozwiązanie zadania minął!",
    captchaTimeoutMore: "Spróbuj ponownie.",
    verifySuccess: "Dziękujemy za potwierdzenie!",
    verifySuccessMore: "Sprawdzamy dane...",
    registerSuccess: "Rejestracja przebiegła pomyślnie!",
    registerSuccessMore: "Na podany adres e-mail wysłaliśmy wiadomość z linkiem do aktywacji Twojego konta.",
    emailAlreadyExists: "Podany adres e-mail jest już przypisany do konta!",
    emailAlreadyExistsMore: "Skorzystaj z opcji logowania bez hasła lub ponownej wysyłki maila aktywacyjnego.",
    unknownError: "Wystąpił nieznany błąd, spróbuj ponownie później.",
    unknownErrorMore: "Jeśli błąd będzie się powtarzał, powiadom nas na serwerze Discord. Kod błędu: {{ 0 }}",
    loginSuccess: "Witamy w panelu zarządzania Ambientem!",
    loginSuccessMore: "Zalogowano pomyślnie.",
    invalidEmailOrPassword: "Podany adres e-mail lub hasło są nieprawidłowe!",
    accountNotActivated: "Twoje konto nie zostało aktywowane!",
    accountNotActivatedMore: "Mail aktywacyjny nie doszedł? Skorzystaj z opcji ponownej wysyłki.",
    loggedOut: "Wylogowano pomyślnie!",
    loggedOutMore: "Dziękujemy za korzystanie z Ambienta.",
    sessionExpired: "Twoja sesja wygasła!",
    sessionExpiredMore: "Zaloguj się ponownie.",
    passwordValidation: {
      min: "Hasło musi składać się z co najmniej 12 znaków.",
      digits: "Hasło musi zawierać co najmniej 2 cyfry.",
      letters: "Hasło musi zawierać co najmniej 6 liter.",
      lowercase: "Hasło musi zawierać co najmniej 3 małe litery.",
      uppercase: "Hasło musi zawierać co najmniej 1 wielką literę.",
      symbols: "Hasło musi zawierać co najmniej 1 znak specjalny.",
      spaces: "Hasło nie może zawierać spacji.",
    },
  },
  profile: {
    infoCardTitle: "Informacje o koncie",
    accountCreationDate: "Data utworzenia konta",
  },
  bots: {
    createBot: "Utwórz nowego bota",
    botName: "Nazwa bota",
    accountName: "Nazwa konta",
    createBotModalHint: "Podaj nazwę dla swojego nowego bota, możesz ją później zmienić.",
    createdSuccessfully: "Bot został pomyślnie utworzony!",
    createdSuccessfullyMore: "Możesz teraz połączyć go z kontem na Facebooku.",
    limitReached: "Posiadasz już maksymalną ilość botów!",
    limitReachedMore: "Usuń niepotrzebne boty lub skorzystaj z istniejącego.",
    nameAlreadyUsed: "Wybrana nazwa jest już zajęta!",
    action: "Akcja",
    manage: "Zarządzaj",
    backToList: "Powrót do listy botów",
    backToView: "Powrót do widoku bota",
    invalidBot: "Wybrany bot nie istnieje!",
    profilePicture: "Zdjęcie profilowe",
    info: "Informacje",
    events: "Zdarzenia",
    fbAccountId: "ID konta na Facebooku",
    showProfile: "Pokaż profil",
    changeName: "Zmień nazwę",
    state: "Stan",
    done: "Gotowe",
    screenshot: "Zrzut ekranu",
    screenshotModalHint:
      "Zrzut ekranu pozwala sprawdzić, dlaczego nie udało nam się zalogować przy użyciu podanych danych. Jeśli wygląda na to, że są one nieprawidłowe, popraw je i spróbuj ponownie. Podejrzewasz, że proces logowania działa nieprawidłowo? Skontaktuj się z nami na serwerze Discord, przyjrzymy się temu jak najszybciej.",
    connection: "Połączenie z kontem",
    connectionHint: "Połącz bota z kontem na Facebooku, aby rozpocząć korzystanie z niego. Aby skorzystać z tej opcji, bot musi być wyłączony.",
    screenshotHint: "Zrzut ekranu pozwala sprawdzić, co dokładnie poszło nie tak podczas ostatniej próby zalogowania się na konto z użyciem podanych przez Ciebie danych.",
    accountState: "Stan konta",
    botState: "Stan bota",
    start: "Uruchom",
    stop: "Zatrzymaj",
    invalidState: "Nieprawidłowy stan!",
    invalidStateMore: "Wybrany bot znajduje się obecnie w stanie niepozwalającym na łączenie go z kontem.",
    connectionStarted: "Rozpoczęliśmy próbę połączenia bota z kontem!",
    connectionStartedMore: "Potrwa to kilkanaście sekund, aktualny stan oraz rezultat zobaczysz na tej stronie.",
    username: "Nazwa użytkownika",
    twoFactorAuthSwitch: "Logowanie dwuetapowe",
    twoFactorAuthCode: "Kod 2FA",
    usernameTooShort: "Podana nazwa użytkownika jest zbyt krótka!",
    passwordTooShort: "Podane hasło jest zbyt krótkie!",
    codeTooShort: "Podany kod logowania dwuetapowego jest zbyt krótki!",
    connectConfirmButton: "Połącz bota z kontem",
    importantCardCheckbox: "Rozumiem",
    understandNotChecked: "Zapoznaj się z ważnymi informacjami!",
    importantCardTitle: "Ważne! Przeczytaj przed połączeniem:",
    importantCardContents: [
      "Konto może zostać zablokowane przez Facebooka, dlatego nie wykorzystuj swojego głównego konta do łączenia go z botem.",
      "Lepiej użyć konta, które zostało założone jakiś czas temu i było używane w normalny sposób, niż zakładać nowe konto i od razu używać go do łączenia z botem.",
      "Najlepiej sprawdzi się konto założone z użyciem prawdziwych danych i ustawionym prawdziwym zdjęciem profilowym, gdyż będzie możliwa weryfikacja tożsamości, kiedy Facebook tego zażąda.",
      "Zalecamy włączenie logowania dwuetapowego z użyciem kodu 2FA w ustawieniach konta, zwiększy to szansę na pomyślne połączenie bota z kontem i zmniejszy szansę na zablokowanie konta z powodu podejrzanej aktywności.",
      "Nie przechowujemy danych logowania, które podasz. Zostaną one użyte jedynie do zalogowania się na konto przez zautomatyzowane oprogramowanie, w celu próby uzyskania sesji użytkownika, która umożliwi połączenie konta z botem, następnie są one zapominane.",
      "Połączenie bota z kontem zajmie kilkanaście sekund, jeśli napotkamy jakiś problem, otrzymasz dostęp do zrzutu ekranu z etapu logowania, na którym ten wystąpił, możesz wtedy zapoznać się z nim, rozwiązać ewentualny problem z kontem i spróbować ponownie.",
      "Podczas logowania na konto, możesz otrzymać powiadomienie o logowaniu z nowej lokalizacji w przeglądarce Chrome na urządzeniu Xiaomi Redmi Note 8 Pro, pochodzi ono z naszego systemu i należy je zignorować.",
      "Możliwe, że podczas próby zalogowania pojawi się prośba o zatwierdzenie go, i podanie na przykład daty urodzenia podanej przy zakładaniu konta, należy wtedy zalogować się na konto w normalny sposób, odpowiedzieć na pytania zadane przez Facebooka, a następnie spróbować połączyć bota z kontem ponownie.",
    ],
    credentialsCardTitle: "Podaj dane logowania do konta na Facebooku:",
    connConditions: {
      notConnected: "Niepołączone",
      connecting: "Trwa łączenie...",
      connected: "Połączone",
    },
    connConditionsMore: {
      notConnected: "Aby uruchomić bota, najpierw musisz połączyć go z kontem na Facebooku.",
      connecting: "Próbujemy połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, może to potrwać kilkanaście sekund.",
      connected: "Udało nam się połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, możesz go teraz uruchomić.",
    },
    powerConditions: {
      starting: "Uruchamianie...",
      running: "Uruchomiony",
      stopping: "Zatrzymywanie...",
      stopped: "Zatrzymany",
    },
    powerConditionsMore: {
      starting: "Uruchamiamy Twojego bota, może to potrwać kilka minut.",
      running: "Twój bot jest uruchomiony i działa prawidłowo.",
      stopping: "Zatrzymujemy Twojego bota, może to potrwać kilka minut.",
      stopped: "Twój bot jest obecnie zatrzymany. Jeśli konto jest połączone, możesz go uruchomić.",
    },
    connFailedReasons: {
      badRequest: "Nieprawidłowe żądanie",
      badCredentials: "Nieprawidłowe dane",
      unexpectedPage: "Nieoczekiwana strona",
      cUserMissing: "Brak użytkownika",
      twoFactorAuthRequired: "Wymagany kod",
      badTwoFactorAuthCode: "Nieprawidłowy kod",
      unknownError: "Nieznany błąd",
    },
    connFailedReasonsMore: {
      badRequest: "Wysłane żądanie połączenia jest nieprawidłowe, spróbuj ponownie później, a jeśli błąd będzie się powtarzał powiadom nas na serwerze Discord.",
      badCredentials: "Podane dane logowania są nieprawidłowe, popraw je i spróbuj ponownie.",
      unexpectedPage:
        "Podczas automatycznego logowania napotkaliśmy na nieoczekiwaną stronę, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
      cUserMissing: "Uzyskana sesja nie zawiera prawidłowych informacji na temat konta",
      twoFactorAuthRequired: "Udało się zalogować, jednak wymagany jest kod logowania dwuetapowego którego nie otrzymaliśmy od Ciebie.",
      badTwoFactorAuthCode: "Udało się zalogować, jednak podany przez Ciebie kod logowania dwuetapowego jest nieprawidłowy.",
      unknownError:
        "Podczas automatycznego logowania napotkaliśmy nieoczekiwany błąd, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
    },
  },
};

export default language;
