const language = {
  global: {
    switchLanguage: "Zmień język / Switch language",
    en: "angielski / English",
    pl: "polski / Polish",
    currentlyChoosen: "Obecnie wybrany / Currently choosen",
    updateAvailable: "Dostępna jest aktualizacja",
    updateAvailableMore: "Za chwilę nastąpi przeładowanie strony",
    discord: "Serwer Discord",
  },
  pages: {
    activate: "Aktywacja konta",
    auth: "Panel",
    bot: "Zarządzanie botem",
    bots: "Twoje boty",
    connect: "Połącz z kontem",
    help: "Pomoc",
    loading: "Ładowanie...",
    logout: "Wyloguj się",
    home: "Strona główna",
    notFound: "404",
    profile: "Twój profil",
    premium: "Premium",
  },
  subheaders: {
    page: "Strona",
    panel: "Panel",
    other: "Inne",
  },
  activate: {
    inProgress: "Trwa aktywacja Twojego konta...",
    success: "Twoje konto zostało pomyślnie aktywowane!",
    successMore: "Za chwilę nastąpi przekierowanie na stronę logowania.",
    failed: "Aktywacja nie powiodła się!",
    failedExpired: "Twoje konto zostało już aktywowane lub upłynął czas na aktywację konta.",
    failedError: "Wystąpił nieznany błąd, spróbuj ponownie później. Jeśli błąd będzie się powtarzał, powiadom nas na serwerze Discord.",
    yourEmail: "Twój adres e-mail:",
    goNow: "Przejdź teraz",
  },
  auth: {
    loginCardTitle: "Korzystasz już z Ambienta? Zaloguj się:",
    email: "Adres e-mail",
    password: "Hasło",
    passwordRepeat: "Powtórz hasło",
    loginButton: "Zaloguj się",
    forgotPassword: "Nie pamiętasz hasła?",
    forgotPasswordModalHint:
      "Podaj adres e-mail przypisany do Twojego konta, aby otrzymać link umożliwiający zalogowanie się bez hasła. Po zalogowaniu ustawienie nowego hasła będzie możliwe w zakładce Twojego profilu.",
    registerCardTitle: "Nowy w Ambiencie? Zarejestruj się teraz!",
    registerButton: "Zarejestruj się",
    activationMailNotReceived: "Mail aktywacyjny nie doszedł?",
    activationMailModalHint: "Podaj adres e-mail podany przy rejestracji, aby ponownie otrzymać link do aktywacji Twojego konta.",
    checkMailbox: "Sprawdź skrzynkę odbiorczą",
    activationMailError: "Konto nie istnieje, upłynął czas na aktywację, lub zostało już aktywowane!",
    cancel: "Anuluj",
    send: "Wyślij",
    invalidEmail: "Podany adres e-mail jest nieprawidłowy!",
    passwordMismatch: "Podane hasła nie zgadzają się!",
    correctAndTryAgain: "Popraw błędne informacje i spróbuj ponownie.",
    confirmHuman: "Potwierdź, że nie jesteś robotem",
    confirmHumanMore: "Rozwiąż proste zadanie, a następnie kliknij przycisk weryfikuj.",
    captchaNotSolved: "Przerwano rozwiązywanie zadania",
    captchaNotSolvedMore: "Musisz rozwiązać zadanie aby potwierdzić, że nie jesteś robotem. Spróbuj ponownie.",
    captchaTimeout: "Czas na rozwiązanie zadania minął!",
    captchaTimeoutMore: "Spróbuj ponownie.",
    verifySuccess: "Dziękujemy za potwierdzenie!",
    verifySuccessMore: "Sprawdzamy dane...",
    registerSuccess: "Rejestracja przebiegła pomyślnie!",
    registerSuccessMore: "Na podany adres e-mail wysłaliśmy wiadomość z linkiem do aktywacji Twojego konta.",
    emailAlreadyExists: "Podany adres e-mail jest już przypisany do konta!",
    emailAlreadyExistsMore: "Skorzystaj z opcji logowania bez hasła lub ponownej wysyłki maila aktywacyjnego.",
    unknownError: "Wystąpił nieznany błąd, spróbuj ponownie później.",
    unknownErrorMore: "Jeśli błąd będzie się powtarzał, powiadom nas na serwerze Discord. Kod błędu: {{ 0 }}",
    loginSuccess: "Witamy w panelu zarządzania Ambientem!",
    loginSuccessMore: "Zalogowano pomyślnie.",
    invalidEmailOrPassword: "Podany adres e-mail lub hasło są nieprawidłowe!",
    accountNotActivated: "Twoje konto nie zostało aktywowane!",
    accountNotActivatedMore: "Mail aktywacyjny nie doszedł? Skorzystaj z opcji ponownej wysyłki.",
    loggedOut: "Wylogowano pomyślnie!",
    loggedOutMore: "Dziękujemy za korzystanie z Ambienta.",
    sessionExpired: "Twoja sesja wygasła!",
    sessionExpiredMore: "Zaloguj się ponownie.",
    passwordValidation: {
      min: "Hasło musi składać się z co najmniej 12 znaków.",
      digits: "Hasło musi zawierać co najmniej 2 cyfry.",
      letters: "Hasło musi zawierać co najmniej 6 liter.",
      lowercase: "Hasło musi zawierać co najmniej 3 małe litery.",
      uppercase: "Hasło musi zawierać co najmniej 1 wielką literę.",
      symbols: "Hasło musi zawierać co najmniej 1 znak specjalny.",
      spaces: "Hasło nie może zawierać spacji.",
    },
  },
  profile: {
    infoCardTitle: "Informacje o koncie",
    accountCreationDate: "Data utworzenia konta",
  },
  bots: {
    createBot: "Utwórz nowego bota",
    botName: "Nazwa bota",
    accountName: "Nazwa konta",
    createBotModalHint: "Podaj nazwę dla swojego nowego bota, możesz ją później zmienić.",
    createdSuccessfully: "Bot został pomyślnie utworzony!",
    createdSuccessfullyMore: "Możesz teraz połączyć go z kontem na Facebooku.",
    limitReached: "Posiadasz już maksymalną ilość botów!",
    limitReachedMore: "Usuń niepotrzebne boty lub skorzystaj z istniejącego.",
    nameAlreadyUsed: "Wybrana nazwa jest już zajęta!",
    action: "Akcja",
    manage: "Zarządzaj",
    backToList: "Powrót do listy botów",
    invalidBot: "Wybrany bot nie istnieje!",
    profilePicture: "Zdjęcie profilowe",
    info: "Informacje",
    events: "Zdarzenia",
    fbAccountId: "ID konta na Facebooku",
    showProfile: "Pokaż profil",
    changeName: "Zmień nazwę",
    state: "Stan",
    done: "Gotowe",
    screenshot: "Zrzut ekranu",
    screenshotModalHint:
      "Zrzut ekranu pozwala sprawdzić, dlaczego nie udało nam się zalogować przy użyciu podanych danych. Jeśli wygląda na to, że są one nieprawidłowe, popraw je i spróbuj ponownie. Podejrzewasz, że proces logowania działa nieprawidłowo? Skontaktuj się z nami na serwerze Discord, przyjrzymy się temu jak najszybciej.",
    connection: "Połączenie z kontem",
    connectionHint: "Połącz bota z kontem na Facebooku, aby rozpocząć korzystanie z niego. Aby skorzystać z tej opcji, bot musi być wyłączony.",
    screenshotHint: "Zrzut ekranu pozwala sprawdzić, co dokładnie poszło nie tak podczas ostatniej próby zalogowania się na konto z użyciem podanych przez Ciebie danych.",
    states: {
      notConnected: "Niepołączony",
      connecting: "Trwa łączenie...",
      connected: "Połączono",
    },
    statesMore: {
      notConnected: "Aby uruchomić bota, najpierw musisz połączyć go z kontem na Facebooku.",
      connecting: "Próbujemy połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, może to potrwać kilkanaście sekund.",
      connected: "Udało nam się połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, możesz go teraz uruchomić.",
    },
    reasons: {
      badRequest: "Nieprawidłowe żądanie",
      badCredentials: "Nieprawidłowe dane",
      unexpectedPage: "Nieoczekiwana strona",
      cUserMissing: "Brak użytkownika",
      twoFactorAuthRequired: "Wymagany kod",
      badTwoFactorAuthCode: "Nieprawidłowy kod",
      unknownError: "Nieznany błąd",
    },
    reasonsMore: {
      badRequest: "Wysłane żądanie połączenia jest nieprawidłowe, spróbuj ponownie później, a jeśli błąd będzie się powtarzał powiadom nas na serwerze Discord.",
      badCredentials: "Podane dane logowania są nieprawidłowe, popraw je i spróbuj ponownie.",
      unexpectedPage:
        "Podczas automatycznego logowania napotkaliśmy na nieoczekiwaną stronę, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
      cUserMissing: "Uzyskana sesja nie zawiera prawidłowych informacji na temat konta",
      twoFactorAuthRequired: "Udało się zalogować, jednak wymagany jest kod logowania dwuetapowego którego nie otrzymaliśmy od Ciebie.",
      badTwoFactorAuthCode: "Udało się zalogować, jednak podany przez Ciebie kod logowania dwuetapowego jest nieprawidłowy.",
      unknownError:
        "Podczas automatycznego logowania napotkaliśmy nieoczekiwany błąd, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
    },
  },
};

export default language;
