const language = {
  global: {
    switchLanguage: "Zmień język / Switch language",
    en: "angielski / English",
    pl: "polski / Polish",
    currentlyChoosen: "Obecnie wybrany / Currently choosen",
    updateAvailable: "Dostępna jest aktualizacja",
    updateAvailableMore: "Za chwilę nastąpi przeładowanie strony",
    status: "Stan",
    github: "GitHub",
    discord: "Discord",
    noName: "(brak nazwy)",
  },
  pages: {
    activate: "Aktywacja konta",
    auth: "Panel",
    bot: "Zarządzanie botem",
    bots: "Twoje boty",
    connect: "Połącz z kontem",
    help: "Pomoc",
    loading: "Ładowanie...",
    logout: "Wyloguj się",
    home: "Strona główna",
    join: "Zaproszenie do grupy",
    notFound: "404",
    profile: "Twój profil",
    premium: "Premium",
    forgot: "Logowanie bez hasła",
  },
  subheaders: {
    page: "Strona",
    panel: "Panel",
    other: "Inne",
  },
  activate: {
    inProgress: "Trwa aktywacja Twojego konta...",
    success: "Twoje konto zostało pomyślnie aktywowane!",
    successMore: "Możesz teraz przejść na stronę logowania.",
    failed: "Aktywacja nie powiodła się!",
    failedMore: "Twoje konto zostało już aktywowane lub upłynął czas na aktywację konta.",
    yourEmail: "Twój adres e-mail:",
    goNow: "Przejdź teraz",
  },
  forgot: {
    inProgress: "Trwa logowanie na Twoje konto...",
    success: "Pomyślnie zalogowano na Twoje konto!",
    successMore: "Możesz teraz przejść do panelu zarządzania Ambientem.",
    failed: "Logowanie bez hasła nie powiodło się!",
    failedMore: "Link do logowania bez hasła stracił ważność.",
  },
  join: {
    checkingInvite: "Trwa sprawdzanie zaproszenia...",
    resolvedInvite: "Zaproszenie do dołączenia do grupy",
    invalidInvite: "Nie możesz skorzystać z tego zaproszenia!",
    invalidInviteMore: "Zaproszenie nie istnieje lub grupa nie jest połączona z żadnym botem.",
    cardContent1: "Zaproszono Cię do dołączenia do grupy",
    cardContent2: "Podaj link do swojego profilu lub nazwę użytkownika na Facebooku, aby automatycznie dołączyć do tej grupy:",
    maleCount: "Mężczyźni",
    femaleCount: "Kobiety",
    messagesCount: "Wiadomości",
    userBatch: "Link do profilu lub nazwa użytkownika",
    button: "Dołącz do grupy",
    immediateJoin: "Ta grupa nie posiada włączonego trybu ręcznego zatwierdzania członków lub bot jest administratorem, więc uzyskasz dostęp do grupy natychmiastowo.",
    approvalRequired: "Ta grupa posiada włączony tryb ręcznego zatwierdzania członków i bot nie jest administratorem, więc uzyskasz dostęp do grupy po zaakceptowaniu prośby.",
    invitationId: "ID zaproszenia:",
    invalidBatch: "Nieprawidłowe namiary na użytkownika!",
    notFound: "Użytkownik nie został odnaleziony!",
    addedMale: "{0}, zostałeś dodany do grupy!",
    addedFemale: "{0}, zostałaś dodana do grupy!",
    addedMore: "Jeśli nie widzisz jej w konwersacjach, sprawdź folder inne.",
    alreadyAdded: "Jesteś już członkiem tej grupy!",
    premiumRequired: "Bot włączony na tej grupie nie posiada Premium!",
    premiumRequiredMore: "Ta funkcja dostępna jest tylko w Ambiencie Premium.",
    alreadyQueued: "Jesteś już w kolejce!",
    alreadyQueuedMore: "Poproś administratora o zaakceptowanie Twojej prośby o dołączenie.",
    groupFull: "W grupie znajduje się już maksymalna liczba członków!",
    groupFullMore: "Poproś administratora o usunięcie z grupy nieaktywnych członków.",
    queueFull: "Kolejka członków do dołączenia jest już pełna!",
    queueFullMore: "Poproś administratora o rozpatrzenie próśb o dołączenie.",
    privacyIssue: "Nie możemy dodać Cię do grupy!",
    privacyIssueMore: "Sprawdź swoje ustawienia dotyczące prywatności.",
  },
  auth: {
    loginCardTitle: "Korzystasz już z Ambienta? Zaloguj się:",
    email: "Adres e-mail",
    password: "Hasło",
    passwordRepeat: "Powtórz hasło",
    loginButton: "Zaloguj się",
    forgotPassword: "Nie pamiętasz hasła?",
    forgotPasswordModalHint:
      "Podaj adres e-mail przypisany do Twojego konta, aby otrzymać link umożliwiający zalogowanie się bez hasła. Po zalogowaniu ustawienie nowego hasła będzie możliwe w zakładce Twojego profilu.",
    registerCardTitle: "Nowy w Ambiencie? Zarejestruj się teraz!",
    registerButton: "Zarejestruj się",
    activationMailNotReceived: "Mail aktywacyjny nie doszedł?",
    activationMailModalHint: "Podaj adres e-mail podany przy rejestracji, aby ponownie otrzymać link do aktywacji Twojego konta.",
    checkMailbox: "Sprawdź skrzynkę odbiorczą uwzględniając folder SPAM",
    activationMailError: "Konto nie istnieje, upłynął czas na aktywację, lub zostało już aktywowane!",
    forgotMailError: "Konto nie istnieje lub nie zostało aktywowane!",
    cancel: "Anuluj",
    send: "Wyślij",
    invalidEmail: "Podany adres e-mail jest nieprawidłowy!",
    passwordMismatch: "Podane hasła nie zgadzają się!",
    correctAndTryAgain: "Popraw błędne informacje i spróbuj ponownie.",
    confirmHuman: "Potwierdź, że nie jesteś robotem",
    confirmHumanMore: "Rozwiąż proste zadanie, a następnie kliknij przycisk weryfikuj.",
    captchaNotSolved: "Przerwano rozwiązywanie zadania",
    captchaNotSolvedMore: "Musisz rozwiązać zadanie aby potwierdzić, że nie jesteś robotem. Spróbuj ponownie.",
    captchaTimeout: "Czas na rozwiązanie zadania minął!",
    captchaTimeoutMore: "Spróbuj ponownie.",
    verifySuccess: "Dziękujemy za potwierdzenie!",
    verifySuccessMore: "Sprawdzamy dane...",
    registerSuccess: "Rejestracja przebiegła pomyślnie!",
    registerSuccessMore: "Na podany adres e-mail wysłaliśmy wiadomość z linkiem do aktywacji Twojego konta.",
    forgotSuccessMore: "Na podany adres e-mail wysłaliśmy wiadomość z linkiem do logowania bez hasła.",
    registrationDisabled: "Rejestracja jest obecnie wyłączona!",
    registrationDisabledMore: "Dołącz na nasz serwer Discord aby uzyskać więcej informacji.",
    emailAlreadyExists: "Podany adres e-mail jest już przypisany do konta!",
    emailAlreadyExistsMore: "Skorzystaj z opcji logowania bez hasła lub ponownej wysyłki maila aktywacyjnego.",
    unknownError: "Wystąpił nieznany błąd, spróbuj ponownie później.",
    unknownErrorMore: "Jeśli błąd będzie się powtarzał, powiadom nas na serwerze Discord. Kod błędu: {0}",
    loginSuccess: "Witamy w panelu zarządzania Ambientem!",
    loginSuccessMore: "Zalogowano pomyślnie.",
    invalidEmailOrPassword: "Podany adres e-mail lub hasło są nieprawidłowe!",
    accountNotActivated: "Twoje konto nie zostało aktywowane!",
    accountNotActivatedMore: "Mail aktywacyjny nie doszedł? Skorzystaj z opcji ponownej wysyłki.",
    loggedOut: "Wylogowano pomyślnie!",
    loggedOutMore: "Dziękujemy za korzystanie z Ambienta.",
    sessionExpired: "Twoja sesja wygasła!",
    sessionExpiredMore: "Zaloguj się ponownie.",
    passwordValidation: {
      min: "Hasło musi składać się z co najmniej 12 znaków.",
      digits: "Hasło musi zawierać co najmniej 2 cyfry.",
      letters: "Hasło musi zawierać co najmniej 6 liter.",
      lowercase: "Hasło musi zawierać co najmniej 3 małe litery.",
      uppercase: "Hasło musi zawierać co najmniej 1 wielką literę.",
      symbols: "Hasło musi zawierać co najmniej 1 znak specjalny.",
      spaces: "Hasło nie może zawierać spacji.",
    },
  },
  profile: {
    infoCardTitle: "Konto",
    accountCreationDate: "Data utworzenia konta",
    changePassword: "Zmień hasło",
    changePasswordModalHint: "Podaj nowe hasło, a następnie wprowadź je ponownie w celu weryfikacji.",
    newPassword: "Nowe hasło",
    newPasswordRepeat: "Powtórz nowe hasło",
    changedSuccessfully: "Hasło zostało pomyślnie zmienione!",
    changedSuccessfullyMore: "Aby się zalogować musisz skorzystać z nowego hasła.",
    premium: "Premium",
    premiumState: "Stan Premium",
    premiumInactive: "nieaktywne",
    premiumActive: "aktywne do {0}",
    premiumId: "Identyfikator Premium",
    copyToClipboard: "Skopiuj do schowka",
    copiedSuccessfully: "Pomyślnie skopiowano identyfikator Premium!",
    copiedSuccessfullyMore: "Dziękujemy za wspieranie Ambienta.",
    address: "Adres IP",
    browser: "Przeglądarka",
    logDescriptions: {
      registered: "Konto zostało pomyślnie utworzone.",
      activated: "Konto zostało pomyślnie aktywowane.",
      passwordChanged: "Hasło zostało pomyślnie zmienione.",
      forgotRequest: "Wysłano prośbę o link do logowania bez hasła.",
      loginWrongPassword: "Próba zalogowania z użyciem błędnego hasła.",
      loginSuccessUnactivated: "Próba zalogowania przed aktywacją konta.",
      loginSuccessNormal: "Pomyślnie zalogowano z użyciem hasła.",
      loginSuccessPasswordless: "Pomyślnie zalogowano z użyciem linku bez hasła.",
      resendRequest: "Wysłano prośbę o link do aktywacji konta.",
      botCreated: "Pomyślnie utworzono nowego bota.",
    },
  },
  bots: {
    botsEmpty: "Nie posiadasz jeszcze żadnych botów, utwórz nowego aby rozpocząć korzystanie z Ambienta.",
    createBot: "Utwórz nowego bota",
    botName: "Nazwa bota",
    accountName: "Nazwa konta",
    createBotModalHint: "Podaj nazwę dla swojego nowego bota, możesz ją później zmienić.",
    createdSuccessfully: "Bot został pomyślnie utworzony!",
    createdSuccessfullyMore: "Możesz teraz połączyć go z kontem na Facebooku.",
    limitReached: "Posiadasz już maksymalną ilość botów!",
    limitReachedMore: "Usuń niepotrzebne boty lub skorzystaj z istniejącego.",
    limitReachedThreads: "Ten bot posiada już maksymalną ilość dozwolonych grup!",
    limitReachedThreadsMore: "Usuń niepotrzebne grupy, skorzystaj z istniejącej, lub użyj innego bota.",
    nameAlreadyUsed: "Wybrana nazwa jest już zajęta!",
    action: "Akcja",
    manage: "Zarządzaj",
    backToList: "Powrót do listy botów",
    backToView: "Powrót do widoku bota",
    invalidBot: "Wybrany bot nie istnieje!",
    profilePicture: "Zdjęcie profilowe",
    info: "Informacje",
    fbAccountId: "ID konta na Facebooku",
    currentInstance: "Obecna instancja",
    showProfile: "Pokaż profil",
    changeName: "Zmień nazwę",
    allowedThreads: "Dozwolone grupy",
    threadName: "Nazwa grupy",
    threadPhoto: "Zdjęcie grupy",
    participantsCount: "Członkowie",
    adminsCount: "Administratorzy",
    hasThisBot: "Ma tego bota",
    yes: "tak",
    no: "nie",
    invitationLink: "Link do zaproszenia",
    showInvitation: "Pokaż zaproszenie",
    copiedSuccessfully: "Pomyślnie skopiowano link do zaproszenia!",
    copiedSuccessfullyMore: "Możesz teraz przekazać go innym osobom.",
    removeThread: "Usuń grupę",
    remove: "Usuń",
    threadsEmpty: "Żadne dozwolone grupy nie zostały jeszcze dodane.",
    threadsNotRunning: "Aby zarządzać dozwolonymi grupami, bot musi być uruchomiony.",
    threadRemoved: "Grupa została pomyślnie usunięta z listy dozwolonych!",
    threadRemovedMore: "Na tej grupie nie można już korzystać z bota.",
    removeThreadModalHint: "Czy na pewno chcesz usunąć tę grupę z listy dozwolonych? Uniemożliwi to korzystanie w niej z bota wszystkim członkom.",
    threadAdded: "Grupa została pomyślnie dodana do listy dozwolonych!",
    threadAddedMore: "Na tej grupie można teraz korzystać z bota.",
    addThread: "Dodaj grupę",
    add: "Dodaj",
    added: "Dodane",
    addThreadModalHint: "Wybierz grupę, którą chcesz dodać do listy dozwolonych. Umożliwi to korzystanie w niej z bota wszystkim członkom.",
    threadsLoading: "Czekaj, zbieramy informacje na temat grup znajdujących się na liście konwersacji połączonego konta. Może to potrwać kilkanaście sekund...",
    threadsNotFound: "Nie znaleźliśmy żadnych wolnych grup z połączonym kontem w członkach na liście konwersacji.",
    state: "Stan",
    done: "Gotowe",
    screenshot: "Zrzut ekranu",
    screenshotModalHint:
      "Zrzut ekranu pozwala sprawdzić, dlaczego nie udało nam się zalogować przy użyciu podanych danych. Jeśli wygląda na to, że są one nieprawidłowe, popraw je i spróbuj ponownie. Podejrzewasz, że proces logowania działa nieprawidłowo? Skontaktuj się z nami na serwerze Discord, przyjrzymy się temu jak najszybciej.",
    connection: "Połączenie z kontem",
    connectionHint: "Połącz bota z kontem na Facebooku, aby rozpocząć korzystanie z niego. Aby skorzystać z tej opcji, bot musi być wyłączony.",
    screenshotHint: "Zrzut ekranu pozwala sprawdzić, co dokładnie poszło nie tak podczas ostatniej próby zalogowania się na konto z użyciem podanych przez Ciebie danych.",
    accountState: "Stan konta",
    botState: "Stan bota",
    start: "Uruchom",
    stop: "Zatrzymaj",
    invalidState: "Nieprawidłowy stan!",
    invalidStateMore: "Wybrany bot znajduje się obecnie w stanie niepozwalającym na łączenie go z kontem.",
    connectionStarted: "Rozpoczęliśmy próbę połączenia bota z kontem!",
    connectionStartedMore: "Potrwa to kilkanaście sekund, aktualny stan oraz rezultat zobaczysz na tej stronie.",
    username: "Adres e-mail lub nr. tel.",
    twoFactorAuthSwitch: "Logowanie dwuetapowe (zalecane)",
    twoFactorAuthCode: "Kod 2FA",
    usernameTooShort: "Podana nazwa użytkownika jest zbyt krótka!",
    passwordTooShort: "Podane hasło jest zbyt krótkie!",
    codeTooShort: "Podany kod logowania dwuetapowego jest zbyt krótki!",
    connectConfirmButton: "Połącz bota z kontem",
    importantCardCheckbox: "Rozumiem",
    understandNotChecked: "Zapoznaj się z ważnymi informacjami!",
    importantCardTitle: "Ważne! Przeczytaj przed połączeniem:",
    importantCardContents: [
      "Konto może zostać zablokowane przez Facebooka, dlatego nie wykorzystuj swojego głównego konta do łączenia go z botem.",
      "Lepiej użyć konta, które zostało założone jakiś czas temu i było używane w normalny sposób, niż zakładać nowe konto i od razu używać go do łączenia z botem.",
      "Najlepiej sprawdzi się konto założone z użyciem prawdziwych danych i ustawionym prawdziwym zdjęciem profilowym, gdyż będzie możliwa weryfikacja tożsamości, kiedy Facebook tego zażąda.",
      "Zalecamy włączenie logowania dwuetapowego z użyciem kodu 2FA w ustawieniach konta, zwiększy to szansę na pomyślne połączenie bota z kontem i zmniejszy szansę na zablokowanie konta z powodu podejrzanej aktywności.",
      "Nie przechowujemy danych logowania, które podasz. Zostaną one użyte jedynie do zalogowania się na konto przez zautomatyzowane oprogramowanie, w celu próby uzyskania sesji użytkownika, która umożliwi połączenie konta z botem, następnie są one zapominane.",
      "Połączenie bota z kontem zajmie kilkanaście sekund, jeśli napotkamy jakiś problem, otrzymasz dostęp do zrzutu ekranu z etapu logowania, na którym ten wystąpił, możesz wtedy zapoznać się z nim, rozwiązać ewentualny problem z kontem i spróbować ponownie.",
      "Podczas logowania na konto, możesz otrzymać powiadomienie o logowaniu z nowej lokalizacji w przeglądarce Safari na urządzeniu iPhone, pochodzi ono z naszego systemu i należy je zignorować.",
      "Możliwe, że podczas próby zalogowania pojawi się prośba o zatwierdzenie go, i podanie na przykład daty urodzenia podanej przy zakładaniu konta, należy wtedy zalogować się na konto w normalny sposób, odpowiedzieć na pytania zadane przez Facebooka, a następnie spróbować połączyć bota z kontem ponownie.",
    ],
    credentialsCardTitle: "Podaj dane logowania do konta na Facebooku:",
    connConditions: {
      notConnected: "Niepołączone",
      connecting: "Trwa łączenie...",
      connected: "Połączone",
    },
    connConditionsMore: {
      notConnected: "Aby uruchomić bota, najpierw musisz połączyć go z kontem na Facebooku.",
      connecting: "Próbujemy połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, może to potrwać kilkanaście sekund.",
      connected: "Udało nam się połączyć bota z kontem na Facebooku przy użyciu podanych przez Ciebie danych logowania, możesz go teraz uruchomić.",
    },
    powerConditions: {
      starting: "Uruchamianie...",
      running: "Uruchomiony",
      stopping: "Zatrzymywanie...",
      stopped: "Zatrzymany",
    },
    powerConditionsMore: {
      starting: "Uruchamiamy Twojego bota, może to potrwać kilkanaście sekund.",
      running: "Twój bot jest uruchomiony i działa prawidłowo.",
      stopping: "Zatrzymujemy Twojego bota, może to potrwać kilkanaście sekund.",
      stopped: "Twój bot jest obecnie zatrzymany. Jeśli konto jest połączone, możesz go uruchomić.",
    },
    connFailedReasons: {
      badRequest: "Nieprawidłowe żądanie",
      badCredentials: "Nieprawidłowe dane",
      unexpectedPage: "Nieoczekiwana strona",
      cUserMissing: "Brak użytkownika",
      twoFactorAuthRequired: "Wymagany kod",
      badTwoFactorAuthCode: "Nieprawidłowy kod",
      unknownError: "Nieznany błąd",
      alreadyUsed: "Zajęte konto",
    },
    connFailedReasonsMore: {
      badRequest: "Wysłane żądanie połączenia jest nieprawidłowe, spróbuj ponownie później, a jeśli błąd będzie się powtarzał powiadom nas na serwerze Discord.",
      badCredentials: "Podane dane logowania są nieprawidłowe, popraw je i spróbuj ponownie.",
      unexpectedPage:
        "Podczas automatycznego logowania napotkaliśmy na nieoczekiwaną stronę, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
      cUserMissing: "Uzyskana sesja nie zawiera prawidłowych informacji na temat konta",
      twoFactorAuthRequired: "Udało się zalogować, jednak wymagany jest kod logowania dwuetapowego którego nie otrzymaliśmy od Ciebie.",
      badTwoFactorAuthCode: "Udało się zalogować, jednak podany przez Ciebie kod logowania dwuetapowego jest nieprawidłowy.",
      unknownError:
        "Podczas automatycznego logowania napotkaliśmy nieoczekiwany błąd, przejrzyj zrzut ekranu i powiadom nas na serwerze Discord jeśli podejrzewasz, że proces logowania działa nieprawidłowo.",
      alreadyUsed: "Udało się zalogować, ale te konto jest już używane przez innego bota. Spróbuj ponownie korzystając z innego konta.",
    },
    events: "Zdarzenia",
    date: "Data",
    description: "Opis",
    logsEmpty: "Nie odnotowano jeszcze żadnych zdarzeń.",
    logDescriptions: {
      created: "Bot został pomyślnie utworzony.",
      runRequest: "Rozpoczęto uruchamianie na żądanie użytkownika.",
      autoRun: "Rozpoczęto automatyczny start w celu przywrócenia poprzedniego stanu.",
      started: "Bot został pomyślnie uruchomiony i działa prawidłowo.",
      stopRequest: "Rozpoczęto zatrzymywanie na żądanie użytkownika.",
      stoppedLifecycle: "Zatrzymano z powodu osiągnięcia maksymalnego czasu działania.",
      stoppedManual: "Zatrzymano na żądanie użytkownika.",
      stoppedInactivity: "Zatrzymano z powodu braku aktywności przez długi czas.",
      stoppedError: "Zatrzymano z powodu błędu, spróbuj uruchomić bota a jeśli problem powtarza się, połącz ponownie konto.",
      threadAdded: "Dodano grupę do listy dozwolonych.",
      threadRemovedManual: "Usunięto grupę z listy dozwolonych.",
      threadRemovedAuto: "Grupa została usunięta z listy dozwolonych z powodu dodania jej w innym bocie.",
      connectionStarted: "Rozpoczęto próbę połączenia bota z kontem na Facebooku.",
      connectionFailed: "Próba połączenia bota z kontem nie powiodła się.",
      connectionSuccess: "Pomyślnie połączono bota z kontem, możesz go teraz uruchomić.",
    },
  },
};

export default language;
